# Generated by Django 5.1.7 on 2025-03-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found')], max_length=5)),
                ('date_reported', models.DateField(auto_now_add=True)),
                ('contact_info', models.CharField(max_length=100)),
            ],
        ),
    ]
